"""The `AgentRuntime` product boundary (P0.4, issue #11).

One stable abstraction over Garuda's native loop and external coding harnesses.
An external harness is never placed behind `Model` — that would run two agent
loops against each other. Runtimes implement `AgentRuntime`; the orchestrator
above it sees only `RuntimeInfo` and `RuntimeEvent`.
"""

from garuda.runtime.conformance import run_conformance_suite
from garuda.runtime.events import (
    TERMINAL_LIFECYCLE_STATES,
    RuntimeEvent,
    RuntimeEventKind,
)
from garuda.runtime.handoff import HandoffError, HandoffPhase, HandoffTransaction, execute_handoff
from garuda.runtime.protocol import (
    PROTOCOL_VERSION,
    AgentRuntime,
    AgentRuntimeError,
    AuthStatus,
    HealthStatus,
    LifecycleState,
    RuntimeCancelledError,
    RuntimeCapabilities,
    RuntimeClosedError,
    RuntimeInfo,
    RuntimeKind,
    RuntimeNotActiveError,
    RuntimeProtocolError,
    RuntimeStartError,
    RuntimeTimeoutError,
    RuntimeTransitionError,
    check_transition,
)
from garuda.runtime.recovery import (
    RecoveryError,
    RecoveryReport,
    RestartState,
    audit_terminal,
    classify,
    reap_orphans,
    record_cancel,
    record_child,
    recover,
    report_to_dict,
)
from garuda.runtime.registry import (
    BUILTIN_NATIVE_ID,
    ProjectRuntimeRef,
    RegistryError,
    ResolvedRuntime,
    RuntimeManifest,
    RuntimeRegistry,
    parse_global_manifests,
    parse_project_refs,
)
from garuda.runtime.router import (
    RoutingCandidate,
    RoutingDecision,
    RoutingError,
    RoutingRequest,
    authorize_switch,
    candidates_from_discovered,
    record_routing_decision,
    route,
)
from garuda.runtime.session import (
    HANDOFF_STATES,
    SESSION_SCHEMA_VERSION,
    RuntimeSegment,
    UnifiedSession,
    UnifiedSessionError,
    load_unified,
    migrate_legacy_meta,
)

__all__ = [
    "RoutingCandidate",
    "RoutingDecision",
    "RoutingError",
    "RoutingRequest",
    "authorize_switch",
    "candidates_from_discovered",
    "record_routing_decision",
    "route",
    "BUILTIN_NATIVE_ID",
    "HANDOFF_STATES",
    "HandoffError",
    "HandoffPhase",
    "HandoffTransaction",
    "execute_handoff",
    "PROTOCOL_VERSION",
    "SESSION_SCHEMA_VERSION",
    "TERMINAL_LIFECYCLE_STATES",
    "AgentRuntime",
    "AgentRuntimeError",
    "AuthStatus",
    "HealthStatus",
    "LifecycleState",
    "ProjectRuntimeRef",
    "RecoveryError",
    "RecoveryReport",
    "RegistryError",
    "ResolvedRuntime",
    "RestartState",
    "RuntimeCapabilities",
    "RuntimeCancelledError",
    "RuntimeClosedError",
    "RuntimeEvent",
    "RuntimeEventKind",
    "RuntimeInfo",
    "RuntimeKind",
    "RuntimeManifest",
    "RuntimeNotActiveError",
    "RuntimeProtocolError",
    "RuntimeRegistry",
    "RuntimeSegment",
    "RuntimeStartError",
    "RuntimeTimeoutError",
    "RuntimeTransitionError",
    "UnifiedSession",
    "UnifiedSessionError",
    "audit_terminal",
    "check_transition",
    "classify",
    "load_unified",
    "migrate_legacy_meta",
    "parse_global_manifests",
    "parse_project_refs",
    "reap_orphans",
    "record_child",
    "record_cancel",
    "recover",
    "report_to_dict",
    "run_conformance_suite",
]
